#!/bin/sh

# This file lists variables for third-party databases managed by "AM"/AppMan

# Helper function to export database info and update flags
set_db() {
	am_extras_db_name=$1
	am_extras_db_repo=$2
	am_extras_db_info=$3
	am_extras_db_readme="https://raw.githubusercontent.com/ivan-hc/am-extras/main/$am_extras_db_name/${ARCH}.md"

	eval "${am_extras_db_name}_repo=\"$am_extras_db_repo\""
	eval "${am_extras_db_name}_readme=\"$am_extras_db_readme\""
	eval "${am_extras_db_name}_info=\"$am_extras_db_info\""

	[ -n "$am_extras_db_readme" ] && third_party_flags="$third_party_flags --$am_extras_db_name"
}

################################################################################
#	Databases using the generic "AM-SAMPLE-Archive" template (default)
################################################################################

set_db busybox "https://busybox.net" "This database provides the complete set of official BusyBox tools."
#set_db coreutilsh "https://github.com/Samueru-sama/coreutils-sh" "This database provides coreutils wrote using pure sh (not bash)."
set_db gtk3 "https://github.com/ivan-hc/GNOME3-appimages" "This database creates and distributes all GTK3 versions of GNOME apps in AppImage format. Visit https://github.com/ivan-hc/GNOME3-appimages to learn more."
#set_db onebin "https://github.com/nikvdp/1bin" "A wide range of pre-compiled binaries wrote in Rust."
set_db python "https://python-appimage.readthedocs.io" "This database creates and distributes all Python versions in AppImage format, ensuring they can be installed side-by-side and without conflict. Visit https://github.com/niess/python-appimage to learn more."

################################################################################
#	Databases using their own template
################################################################################

if [ -n "$MODULES_PATH" ] && [ -f "$MODULES_PATH/install.am" ]; then

	grep -q "AM-SAMPLE-AppBundle" "$MODULES_PATH/install.am" && set_db appbundle "https://github.com/xplshn/AppBundleHUB" "This database provides AppBundles, similar to Appimages but more portable. Built using PELF: https://github.com/xplshn/pelf."

	grep -q "AM-SAMPLE-soarpkg" "$MODULES_PATH/install.am" && set_db soarpkg "https://github.com/pkgforge/soarpkgs" "Largest collection of static binary packages for the SOAR package manager. Visit https://github.com/pkgforge to learn more."

fi
